controller_list:
  - name: setFollowTrajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
  - name: barrett/follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - bh_j11_joint
      - bh_j12_joint
      - bh_j22_joint
      - bh_j32_joint
      
